Evidence_1264855/Controllers/BranchesController.cs
using Evidence_1264855.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evidence_1264855.Controllers
{
    public class BranchesController : Controller
    {
        //Database Injection Dependency/ db Context
        readonly CompanyDbContext db = null;
        public BranchesController(CompanyDbContext db) { this.db = db; }

        //Index Action
        public IActionResult Index()
        {
            return View(db.Branches.ToList());
        }
        //Create Action
        public IActionResult Create()
        {
            return View();
        }
        //Create Post Action
        [HttpPost]
        public IActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Branches.Add(branch);
                db.SaveChanges();
                return PartialView("_MessegeCreatePartial", true);
            }
            return PartialView("_MessegeCreatePartial", false);
        }
        //Update Action
        public IActionResult Update(int id)
        {
            return View(db.Branches.First(b => b.BranchId == id));
        }
        //Update Post Action
        [HttpPost]
        public IActionResult Update(Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(branch).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_MessegeUpdatePartial", true);
            }
            return PartialView("_MessegeUpdatePartial", false);
        }
        //Delete Action
        public IActionResult Delete(int id)
        {
            return View(db.Branches.First(b => b.BranchId == id));
        }
        //Delete Post Action
        [HttpPost, ActionName("Delete")]
        public IActionResult DoDelete(int id)
        {
            Branch branch = new Branch { BranchId = id };
            if (!db.Employees.Any(e => e.BranchId == id))
            {
                db.Entry(branch).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
                db.SaveChanges();
                return PartialView("_MessegeDeletePartial", true);
            }
            //ModelState.AddModelError("", "You Cann't Delete the Project because it relatated to Employees.");
            //return View(db.Branches.First(b => b.BranchId == Id));
            return PartialView("_MessegeDeletePartial", false);
        }
    }
}

Evidence_1264855/Controllers/EmployeesController.cs
using Evidence_1264855.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Evidence_1264855.Controllers
{
    public class EmployeesController : Controller
    {
        //Database Inject Dependency/ db Context
        readonly CompanyDbContext db = null;
        //for IFormFile this service will use
        readonly IWebHostEnvironment env;
        public EmployeesController(CompanyDbContext db, IWebHostEnvironment env) { this.db = db; this.env = env; }

        //Index Action
        public IActionResult Index()
        {
            return View(db.Employees.Include(b => b.Branches).ToList());
        }
        //Create Action
        public IActionResult Create()
        {
            ViewBag.Branches = db.Branches.ToList();
            return View();
        }
        //Create Post Action
        [HttpPost]
        public IActionResult Create(EmployeeCreateModel emp)
        {
            if (ModelState.IsValid)
            {
                var empNew = new Employee
                {
                    EmployeePicture = "no-pic.png",
                    EmployeeName = emp.EmployeeName,
                    EmployeePhone = emp.EmployeePhone,
                    EmployeeSalary = emp.EmployeeSalary,
                    EmployeeDepartment = emp.EmployeeDepartment,
                    EmployeeJoinDate = emp.EmployeeJoinDate,
                    EmployeeGender = emp.EmployeeGender,
                    Continued = emp.Continued,
                    BranchId = emp.BranchId
                };
                if (emp.EmployeePicture != null && emp.EmployeePicture.Length > 0)
                {
                    string dir = Path.Combine(env.WebRootPath, "Uploads");
                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    string fileName = Guid.NewGuid() + Path.GetExtension(emp.EmployeePicture.FileName);
                    string fullPath = Path.Combine(dir, fileName);
                    FileStream fs = new FileStream(fullPath, FileMode.Create);
                    emp.EmployeePicture.CopyTo(fs);
                    fs.Flush();
                    empNew.EmployeePicture = fileName;
                }
                db.Employees.Add(empNew);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Branches = db.Branches.ToList();
            return View(emp);
        }
        //Update Action
        public IActionResult Update(int id)
        {
            ViewBag.Branches = db.Branches.ToList();
            var emp = db.Employees.Include(b => b.Branches).First(e => e.EmployeeId == id);
            ViewBag.CurrentPicture = emp.EmployeePicture;
            return View(new EmployeeUpdateModel
            {
                EmployeeId = emp.EmployeeId,
                EmployeeName = emp.EmployeeName,
                EmployeePhone = emp.EmployeePhone,
                EmployeeSalary = emp.EmployeeSalary,
                EmployeeDepartment = emp.EmployeeDepartment,
                EmployeeJoinDate = emp.EmployeeJoinDate,
                EmployeeGender = emp.EmployeeGender,
                Continued = emp.Continued,
                BranchId = emp.BranchId
            });
        }
        //Update Post Action
        [HttpPost]
        public IActionResult Update(EmployeeUpdateModel emp)
        {
            var empExist = db.Employees.First(e => e.EmployeeId == emp.EmployeeId);
            if (ModelState.IsValid)
            {
                empExist.EmployeeName = emp.EmployeeName;
                empExist.EmployeePhone = emp.EmployeePhone;
                empExist.EmployeeSalary = emp.EmployeeSalary;
                empExist.EmployeeDepartment = emp.EmployeeDepartment;
                empExist.EmployeeJoinDate = emp.EmployeeJoinDate;
                empExist.EmployeeGender = emp.EmployeeGender;
                empExist.Continued = emp.Continued;
                empExist.BranchId = emp.BranchId;
                if (emp.EmployeePicture != null && emp.EmployeePicture.Length > 0)
                {
                    string dir = Path.Combine(env.WebRootPath, "Uploads");
                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    string fileName = Guid.NewGuid() + Path.GetExtension(emp.EmployeePicture.FileName);
                    string fullPath = Path.Combine(dir, fileName);
                    FileStream fs = new FileStream(fullPath, FileMode.Create);
                    emp.EmployeePicture.CopyTo(fs);
                    fs.Flush();
                    empExist.EmployeePicture = fileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Branches = db.Branches.ToList();
            ViewBag.currentPicture = empExist.EmployeePicture;
            return View(emp);
        }
        //Update Action
        public IActionResult Delete(int id)
        {
            return View(db.Employees.Include(e => e.Branches).First(e => e.EmployeeId == id));
        }
        //Delete Post Action
        [HttpPost, ActionName("Delete")]
        public IActionResult DoDelete(int id)
        {
            var Employee = new Employee { EmployeeId = id };
            db.Entry(Employee).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Info Action
        public ActionResult Info(int id)
        {
            ViewBag.Branches = db.Branches.ToList();
            return View(db.Employees.First(e => e.EmployeeId == id));
        }
        //Info Post Action
        [HttpPost, ActionName("Info")]
        public ActionResult DoInfo(int id)
        {
            return RedirectToAction("Info");
        }
    }
}

Evidence_1264855/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evidence_1264855.Controllers
{
    public class HomeController : Controller
    {
        //Home Index
        public IActionResult Index()
        {
            return View();
        }
    }
}

Evidence_1264855/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Application</title>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/Custom Design/main.css" rel="stylesheet" />
    <style>
        body {
            margin: 0;
            padding: 0;
            border: 0;
        }

        section {
            background-image: url("~/images/bg-set.jpg");
            background-image: url("./images/bg-set.jpg");
            background-color: #cccccc;
            height: 570px;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
            background-position: center;
        }

        .card {
            margin-top: 90px;
            box-shadow: 3px 2px 14px 13px rgba(0,0,0,0.27);
            -webkit-box-shadow: 3px 2px 14px 13px rgba(0,0,0,0.27);
            -moz-box-shadow: 3px 2px 14px 13px rgba(0,0,0,0.27);
            font-size: 12px;
        }

        .card-body {
            background-color: #fff;
            color: black;
        }

        .card-1 {
            margin-top: 200px;
        }

        p {
            margin-top: 20px;
        }

        i {
            margin-right: 10px;
        }
    </style>

</head>
<body>
    @await Html.PartialAsync("_NavbarPartial")
    <section>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="d-flex justify-content-center">
                        <div class="card card-1 ">
                            <div class="card-body">
                                <h2 class="card-title"><i class="fa fa-building-o"></i>Company Application</h2>
                                <p class="card-text text-center">Click the Button below to See details.</p>
                                <a asp-action="Index" asp-controller="Branches" class="btn btn-outline-success"><i class="fa fa-building"></i>Go to Branches</a>
                                <a asp-action="Index" asp-controller="Employees" class="btn btn-outline-success"><i class="fa fa-users"></i>Go to Employees</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="d-flex justify-content-center">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title"><i class="fa fa-file-code-o"></i>MVC Core Exam</h2>
                                <p class="card-text text-center">Feel your written code.</p>
                                <p class="card-text text-center list-group-item-secondary"><i class="fa fa-bookmark"></i>Requirement Filled in Project</p>
                                <ul class="list-group list-group-numbered">
                                    <li class="list-group-item">One to Many RelationShip Database.</li>
                                    <li class="list-group-item ">Database Code First in Model.</li>
                                    <li class="list-group-item">Data Anotation Server Side.</li>
                                    <li class="list-group-item ">Data Anotation Client Side.</li>
                                    <li class="list-group-item">Partial View in Navigation</li>
                                    <li class="list-group-item ">Partial View With  Ajax !!</li>
                                    <li class="list-group-item">Different type of Data Variation.</li>
                                    <li class="list-group-item ">Date Picker in JoinDate Field</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container-fluid">
        <p class="text-center">&copy; @DateTime.Now.Year - Company Application. &nbsp;&nbsp; Develop By: Anamul Haque Sohel. &nbsp;&nbsp; ID: 1264855</p>
    </div>
</body>
</html>